name: Build ppc64le container

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'containers/dockerfile/Dockerfile.manylinux_2_34_ppc64le'
      - 'containers/scripts/install_gosu.sh'
      - 'containers/entrypoint.sh'

jobs:
  build:
    name: Build xgb-ci.manylinux_2_34_ppc64le
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd containers
          docker build \
            -t xgb-ci.manylinux_2_34_ppc64le:main \
            -f dockerfile/Dockerfile.manylinux_2_34_ppc64le \
            .

      - name: Verify image
        run: |
          docker run --rm xgb-ci.manylinux_2_34_ppc64le:main \
            /opt/python/cp312-cp312/bin/python --version
          docker run --rm xgb-ci.manylinux_2_34_ppc64le:main \
            ldd --version | head -1